steps:
  - uses: actions/checkout@v2
  - name: Setup PHP
    uses: shivammathur/setup-php@v2
    with:
      php-version: '8.1'
      tools: composer:v2
  - name: Copy .env
    run: cp .env.example .env.testing
  - name: Install Dependencies
    run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
  - name: Set hostname
    run: echo "127.0.0.1 mysql.test" | sudo tee -a /etc/hosts
  - name: Configure Database Permissions
    run: |
      mysql -h mysql.test -u root -ppassword -e "CREATE USER IF NOT EXISTS 'sail'@'%' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON *.* TO 'sail'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"
  - name: Generate key
    run: php artisan key:generate --env testing
  - name: Execute tests (Unit and Feature tests) via PHPUnit
    run: vendor/bin/phpunit
